### ISSUE TITLE
to apply OIDC auth for kraken

### ISSUE THREAD

**Issue by keyolk** [samsung-cnct/k2#123]
Hi all,
I'm doing some of stuffs to enabling OIDC auth for kubernetes with k2
Submitting the issue to see others idea.

Currently I use coreos's [dex](https://github.com/coreos/dex.git)  for OIDC provider.

To use it on kuberentes,
below flags must be added to api-server
**in api-server-manifest.yaml.jinja2**
``` 
{% if kraken_config.authn.type == 'oidc' %}
    - --oidc-issuer-url=https://dex.kube-system.svc.{{kraken_config.clusterDomain}}
    - --oidc-ca-file=/etc/kubernetes/ssl/dex-ca.pem
    - --oidc-client-id=example-app
    - --oidc-groups-claim=groups
{% endif %}
```

It is OK that the dex not running at the time of apiserver launching.
But the PKI asset must be exist.
And currently kubernetes support https only for OIDC.
What would be proper way to pass the **dex-ca.pem** to master instance ? 

The dex will be provided as a helm chart.
And it would be defined at kraken.config as a service like below

**in config.yaml**
``` 
clusterServices:
  services:
    name: dex
    repo: atlas
    chart: dex
    version: 0.1.0
    namespace: kube-system
    values:
      Dex.Tls.Key: ...
      Dex.Tls.Cert: ...
      Dex.Issuer: ...
      Dex.Connector.Github.Enabled: 
      Dex.Connector.Github.ClientId:
      Dex.Connector.Github.ClientSecret:
      Dex.Connector.Google.Enabled:
      Dex.Connector.Google.ClientId:
      Dex.Connector.Google.ClientSecret:
```

And I gonna put authn fileds to define whether it use oidc provider for authn
**in config.yaml**
```
authn:
  -
  name: oidc
  type: oidc
  service: dex
```

And also add a task to the role
**in kraken.master.docker**
```
 - name: Generate master writefiles oidc pem
   template: src=write_files.oidc.part.jinja2
     dest="{{ config_base | expanduser }}/{{kraken_config.cluster}}/master.write_files.oidc.part"
     when: "kraken_config.authn.type == 'oidc'"
```

How do you think, any better idea ?
