### ISSUE TITLE
Make containerConfig a property of nodepools instead of kubeConfigs

### ISSUE THREAD

**Issue by davidewatson** [samsung-cnct/k2#210]
Currently containerConfigs are used in two different ways within the k2 configuration file: one way for etcd nodes and one way for all other nodes (master, cluster, and special). For example, for etcd* nodes it is specified like so:

```
  etcd:
    -
      name: etcd
      clientPorts: [2379, 4001]
      clusterToken: espouse-monger-rarely
      nodepool: etcd
      peerPorts: [2380]
      ssl: true
      version: v3.0.3
      containerConfig: dockerconfig
    -
      name: etcdEvents
      clientPorts: [2381]
      clusterToken: animism-training-chastity
      nodepool: etcdEvents
      peerPorts: [2382]
      ssl: true
      version: v3.0.3
      containerConfig: dockerconfig
```

However, all other nodes get their container config from their kubeConfig. For example:

```
  kubeConfig:
    -
      name: krakenKubeConfig
      version: v1.5.2
      hyperkubeLocation: gcr.io/google_containers/hyperkube
      containerConfig: dockerconfig
```

The proposal is to decouple containerConfig from kubeConfig and allow each nodepool, including etcd* nodes, to have a different containerConfig. In addition to being more consistent, it will simplify the ansible rendering of drop-ins because we will not have to have multiple loops to render templates which depend on containerConfig. More broadly, one might argue for all properties to be associated with nodepools.
