### ISSUE TITLE
create config fact kubernetes_minor_version

### ISSUE THREAD

**Issue by coffeepac** [samsung-cnct/k2#248]
create a fact named `kubernetes_minor_version` which is the current major.minor pair of kubernetes that is specified in the config file.

e.g. if the config file has:
```
deployment:
  kubeConfig:
    -
      version: v1.5.2
```

`kubernetes_minor_version` should be `v1.5`.  This fact must be available globally.
