### ISSUE TITLE
Publish current k2 config schema

### ISSUE THREAD

**Issue by davidewatson** [samsung-cnct/k2#258]
# Task

The schema outlined in #221 needs to be checked in to the k2recon branch for review. Given the length of it, I expect the review to take one or more weeks. Final changes must be done in time for the first k2 release.

**Comment by davidewatson** [comment]
I am debating whether we should just use straight YAML instead of mixing JSON Pointers with YAML. When this syntax was first considered there was opposition towards YAML anchors. Can anyone with a strong opinion please weigh in here? These are the options:

# YAML with JSON Pointers

```
---
version: v1
deployment:
  clusters:
    -
      name: dewVitalogy
      network: 10.32.0.0/12
      dns: 10.32.0.2
      domain: cluster.local
      providerConfig: { $ref: "#/definitions/providerConfigs/defaultAws" }
      nodePools:
        etcd:
          count: 5
          kubeConfig: { $ref: "#/definitions/kubeConfigs/default" }
          etcdConfig: { $ref: "#/definitions/etcdConfigs/default" }
          containerConfig: { $ref: "#/definitions/containerConfigs/defaultDocker" }
          osConfig: { $ref:  "#/definitions/osConfigs/defaultCoreOs" }
          providerConfig: { $ref: "#/definitions/providerConfigs/defaultAwsEtcd" }
          keyPair: { $ref: "#/definitions/keyPairs/default" }
```

# YAML with Anchors and Aliases

```
---
version: v1
deployment:
  clusters:
    -
      name: dewVitalogy
      network: 10.32.0.0/12
      dns: 10.32.0.2
      domain: cluster.local
      providerConfig: *defaultAws"
      nodePools:
        etcd:
          count: 5
          kubeConfig: *defaultKubeConfig
          etcdConfig: *defaultEtcdConfig
          containerConfig: *defaultContainerConfig
          osConfig: *defaultOsConfig
          providerConfig: *defaultProviderConfig
          keyPair: *defaultKeyPair
```

# YAML with Anchors, Aliases, and Merge Keys

```
---
version: v1
deployment:
  clusters:
    -
      name: dewVitalogy
      network: 10.32.0.0/12
      dns: 10.32.0.2
      domain: cluster.local
      providerConfig: *defaultAws"
      nodePools:
        etcd:
          count: 5
          <<: *defaultNodePool
          etcdConfig: *defaultEtcdConfig
```

**Comment by davidewatson** [comment]
I plan to stick with JSON pointers for now since resolving them after expand config is a two line backwards compatible change. This will allow the ansible task changes needed to restructure the config to be broken up, reviewed separately, and implemented in parallel.

**Comment by joejulian** [comment]
The more I look at it and play with it, I kind-of am leaning toward option 3.

Being a part of the built-in yaml parser means we don't have to reinvent our own DSL, which everyone tries to do and nobody does well. Let's not go there.

The only thing I don't like about it is that the definitions have to come before their use which would move the actual config down to the bottom. For that we could consider making a `config.d` path with the config dependencies.

This does get us the clean organized config file that can be cloud-provider agnostic. It does it in a standardized way. It's easy to implement in ansible without needing to write and maintain our own plugins.

**Comment by joejulian** [comment]
The more I look at it and play with it, I kind-of am leaning toward option 3.

Being a part of the built-in yaml parser means we don't have to reinvent our own DSL, which everyone tries to do and nobody does well. Let's not go there.

The only thing I don't like about it is that the definitions have to come before their use which would move the actual config down to the bottom. For that we could consider making a `config.d` path with the config dependencies.

This does get us the clean organized config file that can be cloud-provider agnostic. It does it in a standardized way. It's easy to implement in ansible without needing to write and maintain our own plugins.

And it looks pretty in vim.

And if @venezia doesn't like this, then he's the one that hates his users. ;)

**Comment by davidewatson** [comment]
I agree. I'd still like to hear a counter argument, but we really want provider specific defaults to live in there own files anyway, and once that's done, the ordering of definitions argument becomes moot.

Another think I like about YAML anchors vs. JSON pointers is that you can anchor a list element and reference it by name vs. pointing to an opaque list index.

**Comment by davidewatson** [comment]
Config file changes were checked in: https://github.com/samsung-cnct/k2/pull/276

**Comment by davidewatson** [comment]
For completeness, this is the format we finally agreed upon:

```
deployment:
  clusters:
    - name: k2recon
      network: 10.32.0.0/12
      dns: 10.32.0.2
      domain: cluster.local
      providerConfig: *defaultAws
      nodePools:
        - name: etcd
          count: 5
          etcdConfig: *defaultEtcd
          containerConfig: *defaultDocker
          osConfig: *defaultCoreOs
          nodeConfig: *defaultAwsEtcdNode
          keyPair: *defaultKeyPair
        - name: etcdEvents
          count: 5
          etcdConfig: *defaultEtcdEvents
          containerConfig: *defaultDocker
          osConfig: *defaultCoreOs
          nodeConfig: *defaultAwsEtcdEventsNode
          keyPair: *defaultKeyPair
        - name: master
          count: 3
          loadBalancerConfig: *defaultLoadBalancer
          apiServerConfig: *defaultApiServer
          kubeConfig: *defaultKube
          containerConfig: *defaultDocker
          osConfig: *defaultCoreOs
          nodeConfig: *defaultAwsMasterNode
          keyPair: *defaultKeyPair
        - name: clusterNodes
          count: 3
          kubeConfig: *defaultKube
          containerConfig: *defaultDocker
          osConfig: *defaultCoreOs
          nodeConfig: *defaultAwsClusterNode
          keyPair: *defaultKeyPair
        - name: specialNodes
          count: 2
          kubeConfig: *defaultKube
          containerConfig: *defaultDocker
          osConfig: *defaultCoreOs
          nodeConfig: *defaultAwsSpecialNode
          keyPair: *defaultKeyPair
      fabricConfig: *defaultCanalFabric
      helmConfig: *defaultHelm
  readiness:
    type: exact
    value: 0
    wait: 600
```

Where the YAML anchors defining things like ```*defaultCoreOs``` are defined before, either within the same file, or possibly within separate files.
