### ISSUE TITLE
Fail depreciated k2 schema

### ISSUE THREAD

**Issue by davidewatson** [samsung-cnct/k2#262]
New:

Schemas are depreciated in whole or not at all. This is a result of the earlier design decision to only version the entire config file and not each individual stanza. This ticket is to add a check to fail the kraken.config role if the schema version claimed by the config file is marked as depreciated. See the comments for more detail.

Old:

# Task

Per #221 , before a property can be removed it must be depreciated first to give the user a chance to stop depending on it. Programmatically this is done by adding the property to the depreciated list within the k2 schema. For example [1] gives a hypothetical schema stanza. Since depreciated is an extension to JSON schema (see [PR #173](https://github.com/json-schema-org/json-schema-spec/pull/173) for the current discussion) no standard validator will print warnings. This ticket is to create an Ansible task which will print warnings as part of the kraken.config role.  

[1]

```yaml
"kubeConfig": {
"title": "A Kubernetes configuration",
"description": "The location and version of a container containing the Kubernetes hyperkube binary.",
"properties": {
"name": {
"default": "defaultKubeConfig",
"description": "Name of the Kubernetes configuration.",
"type": "string"
},
"hyperkubeLocation": {
"default": "gcr.io/google_containers/hyperkube",
"description": "Location of the Kubernetes container.",
"format": "uri",
"type": "string"
},
"version": {
"default": "v1.5.2",
"description": "Version of the hyperkube binary.",
"format": "symver",
"type": "string"
}
},
"required": [
"name"
],
"depreciated": [
"hyperkubeLocation"
],
"type": "object"
},
```
