### ISSUE TITLE
Change the subnet names in the default config file to be more generic

### ISSUE THREAD

**Issue by joejulian** [samsung-cnct/k2#278]
Since the subnet names currently match the aws availability zones, there's a misconception that those are linked to those zones. Change them to something more generic to exemplify the separation between name and zone.

**Comment by davidewatson** [comment]
It's not clear to me that this involves a simple rename:

```
    subnet:
      -
        name: uwswest2a
        az: us-west-2a
        cidr: 10.0.0.0/18
```

Isn't the real problem that, like volumes and volumeMounts, subnets and azs needs to be split apart?
