### ISSUE TITLE
Evaluate Ansible Role Tags for Correct and Missing Usage

### ISSUE THREAD

**Issue by mikeln** [samsung-cnct/k2#391]
The tags specified for each role in the following files need to be evaluated for correct usages, completeness, missing usages, etc...
```
ansible/  
  up.yaml
  down.yaml 
  update.yaml
  upgrade.yml
```

**Comment by davidewatson** [comment]
One tag which does not work correctly at present is dryrun. For example, fabric role will fail with dryrun due to an unnecessary API server health check.

**Comment by blackdog0403** [comment]
all
dryrun
always
config
config_only => do not need both of them
common
common_only => do not need both of them
nodePools
nodePools_only=> do not need both of them
assembler
assembler_only
provider
provider_only
ssh
ssh_only
readiness
readiness_only
fabric
fabric_only
services
services_only

master
master_ony(type?) upgrade.yaml

**Comment by blackdog0403** [comment]
### Usage
User can use certain part of ansible roles under /k2/roles directory through tags

To use tags user should set environment variable : $KRAKEN_TAGS

For exmple. if you can set  $KRAKEN_TAGS as 'dryrun' to run shell script without spinning up clusters
```
$ export KRAKEN_TAGS="dryrun"
```
Or you can set multiple tags using ',' for delimeter

```
$ export KRAKEN_TAGS="fabric_only, services_only"
```

Then you can verify those tags though stdout output when run some commands like 'up.sh'
```
$ docker run $K2OPTS quay.io/samsung_cnct/k2:latest ./up.sh --config $HOME/.kraken/${CLUSTER}.yaml
WARNING: --output not specified. Using /Users/blackdog/.kraken as location
WARNING: Using 'dryrun' as tags
...
```

**Comment by blackdog0403** [comment]
|Tag  / Role  | config | cluster_common  | nodePool/kraken.nodePool.selector | assembler | provider/kraken.provider.selector |  ssh/kraken.ssh.selector | readiness | fabric/kraken.fabric.selector | services |
| -------------- | ------------ | ----------  | ------------ |    ------------ |  ------------ |  ------------ |  ------------ |  ------------ |  ------------ | 
| all | | | | | | | | | |
|dryrun | O | | | | | | | | |
|always | | | | | | | | | |
|config | | | | | | | | | |
|config_only | | | | | | | | | |
|common | | | | | | | | | |
|common_only | | | | | | | | | |
|nodePools | | | | | | | | | |
|nodePools_only | | | | | | | | | |
|assembler | | | | | | | | | |
|assembler_only | | | | | | | | | |
|provider | | | | | | | | | |
|provider_only | | | | | | | | | |
|ssh | | | | | | | | | |
|ssh_only | | | | | | | | | |
|readiness | | | | | | | | | |
|readiness_only | | | | | | | | | |
|fabric | | | | | | | | | |
|fabric_only | | | | | | | | | |
|services | | | | | | | | | |
|services_only | | | | | | | | | |
|master | | | | | | | | | |
|master_ony(type?) | | | | | | | | | |
test

**Comment by blackdog0403** [comment]
```
if [ -z ${KRAKEN_TAGS+x} ]; then
  KRAKEN_TAGS="all"
  warn "$KRAKEN_TAGS not specified. Using 'all' as tags"
else
  warn "Using '${KRAKEN_TAGS}' as tags "
fi
```
added warning logs for better recognition for tags

**Comment by blackdog0403** [comment]
| Role Name  | up.yaml     | down.yaml         | update.yaml  |
| -------------- | ------------ | ----------   | ------------ |
| kraken.config | O | O | O |
| roles.kraken.cluster_common | O |  X | O |
| roles.kraken.nodePool/kraken.nodePool.selector | O | X |  O |
| roles.kraken.assembler | O | X | O |
| roles.kraken.provider/kraken.provider.selector | O | O | O |
| roles.kraken.ssh/kraken.ssh.selector | O | X | O |
| roles.kraken.readiness | O | X | O |
| roles.kraken.fabric/kraken.fabric.selector | O | X | O |
| roles.kraken.services | O |  O | X |
| roles.kraken.clean |  X | O | X |

**Comment by blackdog0403** [comment]
@davidewatson Could you give some logs for it? I tried dryrun tag with up.sh but didn't find that sort of problem

**Comment by blackdog0403** [comment]
```
- name: Wait for api server
  wait_for:
    host: "{{ item | regex_replace('https://','') }}"
    port: 443
    timeout: 600
  with_items: "{{ api_servers }}"
  vars:
    kubefn: "{{ config_base | expanduser }}/{{ cluster.name }}/admin.kubeconfig"
    kubeconfig: "{{ kubefn | is_file | ternary( kubefn, '/dev/null' ) }}"
    api_servers: "{{ lookup('file', kubeconfig) | from_yaml | json_query('clusters[*].cluster.server') }}"
  when: "{{ not (dryrun | bool) }}"
```
