### ISSUE TITLE
Running up.sh command with 'dryrun' tags leads spinning up actual cluster

### ISSUE THREAD

**Issue by blackdog0403** [samsung-cnct/k2#480]
Running up.sh command with 'dryrun' tags leads spinning up actual cluster.

It runs ansible roles under a k2/ansible/roles/kraken.provider/ directory so that it spins up actual cluster

Need to change codes below

k2/ansible/roles/kraken.provider/kraken.provider.aws/tasks/main.yaml

k2/ansible/roles/kraken.provider/kraken.provider.gke/tasks/create-cluster.yaml

In case of role for GKE, it needs to take the task for "Render a deployment manager template" out to main.yml for dryrun test

#391 should be updated with issue.

**Comment by joejulian** [comment]
actually, it is supposed to run those roles as those roles create the cloud-init files which is a process that needs to happen during dryrun.

The dryrun does execute without bringing up a cluster if you run (as it does in Jenkinsfile):
```./up.sh --config $PWD/cluster/aws/config.yaml --output $PWD/cluster/aws/ -t dryrun```

**Comment by blackdog0403** [comment]
@joejulian Yes, it should just run roles which render cloud-init files or modules for terraform but at the moment rund aws-action.yaml which runs terraform modules.

**Comment by joejulian** [comment]
I was just seeing that in master. I stand corrected.

**Comment by joejulian** [comment]
changed in commit f7b6d15f

**Comment by blackdog0403** [comment]
Oh there it is. I checked up.yaml file history but looks like it was change from recon but not

**Comment by blackdog0403** [comment]
k2/ansible/roles/kraken.fabric/kraken.fabric.flannel/tasks/main.yaml

```
- name: Wait for api server
 wait_for:
   host: "{{ item | regex_replace('https://','') }}"
   port: 443
   timeout: 600
 with_items: "{{ api_servers }}"
 vars:
   kubefn: "{{ config_base | expanduser }}/{{ cluster.name }}/admin.kubeconfig"
   kubeconfig: "{{ kubefn | is_file | ternary( kubefn, '/dev/null' ) }}"
   api_servers: "{{ lookup('file', kubeconfig) | from_yaml | json_query('clusters[*].cluster.server') }}"
 when: not ( dryrun | bool )
```
error log

```
fatal: [localhost]: FAILED! => {"failed": true, "msg": "{{ lookup('file', kubeconfig) | from_yaml | json_query('clusters[*].cluster.server') }}: An unhandled exception occurred while running the lookup plugin 'file'. Error was a <class 'ansible.errors.AnsibleError'>, original message: could not locate file in lookup: /Users/blackdog/.kraken/cappuccino/admin.kubeconfig"}
```

**A task that includes 'vars' get evaluated even if conditonal exists for the task.**

```
Note that if you have several tasks that all share the same conditional statement, you can affix the conditional to a task include statement as below. All the tasks get evaluated, but the conditional is applied to each and every task:
```


I added conditional in #501 for terraform module in file below 
k2/ansible/roles/kraken.provider/kraken.provider.aws/tasks/main.yaml
```
...
- include: aws-action.yaml
  when: not ( dryrun | bool )
...
```

k2/ansible/roles/kraken.provider/kraken.provider.aws/tasks/aws-action.yaml

Is supposed to set 'kraken_endpoint', Because it's not executed in case of using 'dryrun' tag.
```
...
- name: Set the kraken end point fact
  set_fact:
    kraken_endpoint: "{{ endpoint_result.stdout }}"
  when: endpoint_result | succeeded and not endpoint_result | skipped
...
```

So that "kraken_endpoint" is not defined because of not running terraform modules in aws-action.yaml

k2/ansible/roles/kraken.access/tasks/setup-certs.yaml

```
...
- include: generate-admin-kubeconfig.yaml
  when: kraken_endpoint is defined
...
```
Then generate-admin-kubeconfig.yaml doesn't generate admun.kubeconfig file.

k2/ansible/roles/kraken.fabric/kraken.fabric.flannel/tasks/main.yaml
```
- name: Wait for api server
  wait_for:
    host: "{{ item | regex_replace('https://','') }}"
    port: 443
    timeout: 600
  with_items: "{{ api_servers }}"
  vars:
    kubefn: "{{ config_base | expanduser }}/{{ cluster.name }}/admin.kubeconfig"
    kubeconfig: "{{ kubefn | is_file | ternary( kubefn, '/dev/null' ) }}"
    api_servers: "{{ lookup('file', kubeconfig) | from_yaml | json_query('clusters[*].cluster.server') }}"
  when: not ( dryrun | bool )
```

It occurs error due to admin.kubeconfig doesn't exist on dryrun.
