### ISSUE TITLE
Add Missing Config Items Required for 1.6 RBAC Enable

### ISSUE THREAD

**Issue by mikeln** [samsung-cnct/k2#491]
Missed in the initial checkin.

Need `rbac` defined
Need `authn.basic..group` set.

```
 - &rbacKubeAuth
      authz:
        rbac: 1
      authn:
        basic:
          -
            password: "BadPassword"
            user: "admin"
            group: "system:masters"
        default_basic_user: "admin"
```

in 1.5:
```
 - &rbacKubeAuth
      authz:
        rbac: 1
        super_user: <some super user value>
      authn:
        basic:
          -
            password: "BadPassword"
            user: "admin"
            group: "system:masters"
        default_basic_user: "admin"
```
