### ISSUE TITLE
Dryrun fails at "Wait for api server" tasks in kraken.fabric.flannel role

### ISSUE THREAD

**Issue by blackdog0403** [samsung-cnct/k2#515]
k2/ansible/roles/kraken.fabric/kraken.fabric.flannel/tasks/main.yaml

```
- name: Wait for api server
  wait_for:
    host: "{{ item | regex_replace('https://','') }}"
    port: 443
    timeout: 600
  with_items: "{{ api_servers }}"
  vars:
    kubefn: "{{ config_base | expanduser }}/{{ cluster.name }}/admin.kubeconfig"
    kubeconfig: "{{ kubefn | is_file | ternary( kubefn, '/dev/null' ) }}"
    api_servers: "{{ lookup('file', kubeconfig) | from_yaml | json_query('clusters[*].cluster.server') }}"
  when: not ( dryrun | bool )
```
error log

```
fatal: [localhost]: FAILED! => {"failed": true, "msg": "{{ lookup('file', kubeconfig) | from_yaml | json_query('clusters[*].cluster.server') }}: An unhandled exception occurred while running the lookup plugin 'file'. Error was a <class 'ansible.errors.AnsibleError'>, original message: could not locate file in lookup: /Users/blackdog/.kraken/cappuccino/admin.kubeconfig"}
```

**A task that includes 'vars' get evaluated even if conditonal exists for the task.**

```
Note that if you have several tasks that all share the same conditional statement, you can affix the conditional to a task include statement as below. All the tasks get evaluated, but the conditional is applied to each and every task:
```

**Comment by blackdog0403** [comment]
I added conditional for terraform module in file below

k2/ansible/roles/kraken.provider/kraken.provider.aws/tasks/main.yaml
```
...
- include: aws-action.yaml
  when: not ( dryrun | bool )
...
```

k2/ansible/roles/kraken.provider/kraken.provider.aws/tasks/aws-action.yaml

Is supposed to set 'kraken_endpoint', Because it's not executed in case of using 'dryrun' tag.
```
...
- name: Set the kraken end point fact
  set_fact:
    kraken_endpoint: "{{ endpoint_result.stdout }}"
  when: endpoint_result | succeeded and not endpoint_result | skipped
...
```

So that "kraken_endpoint" is not defined because of not running terraform modules in aws-action.yaml

k2/ansible/roles/kraken.access/tasks/setup-certs.yaml

```
...
- include: generate-admin-kubeconfig.yaml
  when: kraken_endpoint is defined
...
```
Then generate-admin-kubeconfig.yaml doesn't generate admun.kubeconfig file.

k2/ansible/roles/kraken.fabric/kraken.fabric.flannel/tasks/main.yaml
```
- name: Wait for api server
  wait_for:
    host: "{{ item | regex_replace('https://','') }}"
    port: 443
    timeout: 600
  with_items: "{{ api_servers }}"
  vars:
    kubefn: "{{ config_base | expanduser }}/{{ cluster.name }}/admin.kubeconfig"
    kubeconfig: "{{ kubefn | is_file | ternary( kubefn, '/dev/null' ) }}"
    api_servers: "{{ lookup('file', kubeconfig) | from_yaml | json_query('clusters[*].cluster.server') }}"
  when: not ( dryrun | bool )
```

It occurs error due to admin.kubeconfig doesn't exist on dryrun.
