### ISSUE TITLE
Potential issues with kubedns + weave-net

### ISSUE THREAD

**Issue by alejandroEsc** [samsung-cnct/k2#546]
It is unclear yet how common/uncommon this is, or even if it is necessarily an issue:

on https://github.com/samsung-cnct/k2/pull/538 we have mentioned that the following steps:

1. Run a k2 cluster up
2. Run busybox, choose your flavor
3. Run `kubectl exec -it <busybox-pod> -- traceroute kubernetes.default`

(note using https://hub.docker.com/r/radial/busyboxplus/ image atm)

You should expect to see something like

*expected*

```
traceroute to kubernetes.default (10.32.0.1), 30 hops max, 46 byte packets
 1  kubernetes.default.svc.cluster.local (10.32.0.1)  0.309 ms  0.178 ms  0.167 ms
```

*ocassional error:*
```
traceroute to 10.32.0.2 (10.32.0.2), 30 hops max, 46 byte packets
 1  busybox (10.36.0.1)  3099.407 ms !H  3071.823 ms !H  3071.873 ms !H
```

I have seen this only in weave-net 1.9.7, but @mikeln says he has seen it a few times on 1.9.8. I have yet to see it, so more testing has to be done.

*Next Steps:*

1. Test and determine if this is a weave-net issue or k2  issue
2. File bug(s)
3. Make appropriate changes to mitigate.

**Comment by alejandroEsc** [comment]
Labels may need to be changed, depending on team's decision.

**Comment by mikeln** [comment]
DNS symptoms. 1) nslookup from a pod using default kubeDNS service IP (10.32.0.2) does not resolve.  2) nslookup from a pod using the actual kubdns endpoint IP (varies) does resolve.

traceroute: 1) from pod to service IP give !H (as stated above),  2) from pod to endpoint IP successfully shows route.

My experience, 1.9.8, does not work.  restarted kubedns, fabric in different combinations/times on a given running cluster.  Very infrequently, with kubeDNS start working (1 in 30).  Not sure what fixes the issue.

**Comment by alejandroEsc** [comment]
very weird, 1/30 has not been my experience. I seriously have 100% rate at this time, could you describe your testing, going to try to do it manually then automate it and see what the success failure rate is. Also, even if we do not agree 1.9.8 helps, we do need the fixes described in that release.

**Comment by mikeln** [comment]
testing.  bring up 1.6 cluster running weave 1.9.8.   
add a busybox pod.
use pod to nslookup kubernetes.defualt.  
use pod to traceroute.

delete/apply -f kubedns,  delete weave pods directly (restarted by daemonset), delete/apply -f weave.
etc.

**Comment by alejandroEsc** [comment]
@mikeln there are several use cases here we are conflating different stories.

* Weave networking should work on cluster up.
* Weave networking should tolerate kubeDNS restarted
* Weave networking should tolerate external pod restarted 
* Weave networking should tolerate its pods on any nodes restarted
* Weave networking should work after removing and recreating daemonset.

Could you identify which of the above should i try to target first? I think the pods on each node being kicked is probably a good start.

**Comment by mikeln** [comment]
The only issue is that it isn't working on cluster up.  

All the other items where an attempt to get it working, not causing additional problems.  The only time I've got it to work, was after a number of reboots of certain things (unspecific).

**Comment by alejandroEsc** [comment]
@mikeln sorry for being so pendantic, but i needed to understand. Ok, cluster up is the issue, that pinpoints things for me a ton. Can you send me a copy of the config file you are using?

**Comment by mikeln** [comment]
relavant values:  kube version: 1.6.4, weave 1.9.8, rbacKubeAuth
nothing special.

**Comment by alejandroEsc** [comment]
Could i get the cluster stanza you are using, and the rbackUbeAuth stanza.

**Comment by mikeln** [comment]
Those are the default ones. The only change is to point the fabric at versioned weave.
```
deployment:
  clusters:
    - name: mikeln-wv
      network: 10.32.0.0/12
      dns: 10.32.0.2
      domain: cluster.local
      providerConfig: *defaultAws
      nodePools:
        - name: etcd
          count: 5
          etcdConfig: *defaultEtcd
          containerConfig: *defaultDocker
          osConfig: *defaultCoreOs
          nodeConfig: *defaultAwsEtcdNode
          keyPair: *defaultKeyPair
        - name: etcdEvents
          count: 5
          etcdConfig: *defaultEtcdEvents
          containerConfig: *defaultDocker
          osConfig: *defaultCoreOs
          nodeConfig: *defaultAwsEtcdEventsNode
          keyPair: *defaultKeyPair
        - name: master
          count: 3
          apiServerConfig: *defaultApiServer
          kubeConfig: *defaultKube
          containerConfig: *defaultDocker
          osConfig: *defaultCoreOs
          nodeConfig: *defaultAwsMasterNode
          keyPair: *defaultKeyPair
        - name: clusterNodes
          count: 3
          kubeConfig: *defaultKube
          containerConfig: *defaultDocker
          osConfig: *defaultCoreOs
          nodeConfig: *defaultAwsClusterNode
          keyPair: *defaultKeyPair
        - name: specialNodes
          count: 2
          kubeConfig: *defaultKube
          containerConfig: *defaultDocker
          osConfig: *defaultCoreOs
          nodeConfig: *defaultAwsSpecialNode
          keyPair: *defaultKeyPair
      fabricConfig: *kubeVersionedWeaveFabric
      kubeAuth: *rbacKubeAuth
      helmConfig: *defaultHelm
      dnsConfig: *defaultDns
      helmOverride: false
  readiness:
    type: exact
    value: 0
    wait: 600
```
