### ISSUE TITLE
Calico Node Version Update

### ISSUE THREAD

**Issue by mikeln** [samsung-cnct/k2#604]
In our source for Canal fabric: https://github.com/projectcalico/canal/blob/master/k8s-install/1.6/canal.yaml
the Calico Node version has been updated:
```
- name: calico-node
   image: quay.io/calico/node:v1.2.1
```

We should update our default version number accordingly in:
ansible/roles/kraken.config/files/config.yaml, gke-config.yaml
```
- &defaultCanalFabric16
      name: defaultCanalFabric16
      kind: fabric
      type: canal
      options:
        containers:
          calicoCni:
            version: v1.8.3
            location: quay.io/calico/cni
          calicoNode:
            version: v1.1.3                    <---- v1.2.1
            location: quay.io/calico/node
          flannel:
            version: v0.7.1
            location: quay.io/coreos/flannel
```
