### ISSUE TITLE
DNS Service Modification for Master Node Taints

### ISSUE THREAD

**Issue by mikeln** [samsung-cnct/k2#612]
According to: https://github.com/samsung-cnct/k2-charts/issues/107 

> Once samsung-cnct/k2#588 is merged, any charts that need to run in the master nodepool will need to include tolerations for this master taint.
```
tolerations:
 - key: node-role.kubernetes.io/master
   operator: Equal
   effect: NoSchedule
 - operator: Exists
```

These changes will need to be applied to the DNS service.
