### ISSUE TITLE
ansible ec2_elb_facts doesn't use the credentials file

### ISSUE THREAD

**Issue by coffeepac** [samsung-cnct/k2#628]
according to this page:  http://docs.ansible.com/ansible/ec2_elb_facts_module.html there is no option to use the aws credentials file.  We allow a user to specify only a credentials file, which would then not get used for querying the ELBs.

I am somewhat at a loss as to how this ever worked unless there is something in K2 that exports the values in the credentials file into the environment?

**Comment by davidewatson** [comment]
Huh. This should be fixed.

Ansible uses the boto configuration file if no credentials are provided. This includes `~/.aws` et al. The [documentation](http://boto.readthedocs.io/en/latest/boto_config_tut.html) contains more.

Notes
------

The default config:

```
      authentication:
        accessKey:
        accessSecret:
        credentialsFile: "$HOME/.aws/credentials"
        credentialsProfile:
```

The kraken.ssh role which depends on it:

```
- name: Gather inventory of all cluster nodes
  ec2_remote_facts:
    region: "{{ cluster.providerConfig.region }}"
    aws_access_key: "{{ cluster.providerConfig.authentication.accessKey or omit }}"
    aws_secret_key: "{{ cluster.providerConfig.authentication.accessSecret or omit }}"
    profile: "{{ cluster.providerConfig.authentication.credentialsProfile or omit }}"
    filters:
      "tag:k2-nodepool": "{{ item.name }}"
      "tag:Name": "{{ cluster.name }}_{{ item.name }}*"
  with_items: "{{ cluster.nodePools }}"
  register: ec2_results
```
