### ISSUE TITLE
Register Custom Domain In AWS ELB for Kuberenetes API Server

### ISSUE THREAD

**Issue by sostheim** [samsung-cnct/k2#636]
As a Cluster Operator on AWS Cloud Provider infrastructure, I want to be able to install a friendly domain name on the AWS ELB (public and private), to accept secure connections.

**Comment by sostheim** [comment]
This would be particularly useful for managing the A/CNAME record associated with a consistent API server endpoint.

```
- cluster:
    certificate-authority-data: *** REDACTED *** 
    server: https://ras-cts-master-elb-1892227221.us-west-2.elb.amazonaws.com
  name: ras-cts
```
Would be more easily managed with a CNAME that the operations group can point to the appropriate ELB.

```
- cluster:
    certificate-authority-data: *** REDACTED *** 
    server: https://ras-cts-production.mydomain.com
  name: ras-cts
```
