### ISSUE TITLE
Allow Configurable Enable/Disable of BasicAuth and Certificate Auth

### ISSUE THREAD

**Issue by mikeln** [samsung-cnct/k2#643]
Add a configuration value to enable/disable BasicAuth.
Add a configuration value to enable/disable CertAuth.

Default: CertAuth enabled and BasicAuth disabled.

Generate `<user>.kubeconfig` files for each user defined in the config file `authn` section.
Always generate an `admin.kubeconfig` with the `admin` user (as specified by the `default_basic_user`).

**Comment by mikeln** [comment]
Follow on from rbac

**Comment by mikeln** [comment]
A couple config choices to avoid breaking changes.

Clearest is adding a new section for users that should have `cert` auth.  However, this may result in duplication of the user data.  
```
 - &rbacKubeAuth
      authz:
        rbac:
          # super_user is required until kubernetes 1.5 is no longer supported by k2.
          # It is not used by kubernetes 1.6 or later.
          super_user: "placeholder"
      authn:
        basic:
          -
            password: "FlusterFools"
            user: "admin"
            group: "system:masters"
          -
            password: "FlusterFoolers2"
            user: "basicuser2"
            group: "mybasicuser2"
        cert:
          -
            user: "admin"
            group: "system:masters"
          -
            user: "nopriv"
            group: "system:basic-user"
          -
            user: "certuser2"
            group: "mycertuser2"
        default_basic_user: "admin"
```

Different setup to avoid user duplication and breaking changes.  However, the list of users usage is unclear, and certain fields are not needed for cert only.
```
 - &rbacKubeAuth
      authz:
        rbac:
          # super_user is required until kubernetes 1.5 is no longer supported by k2.
          # It is not used by kubernetes 1.6 or later.
          super_user: "placeholder"
      authn:
        basic:
          -
            password: "FlusterFools"
            user: "admin"
            group: "system:masters"
          -
            password: "FlusterFoolers"
            user: "nopriv"
            group: "system:basic-user"
          -
            password: "FlusterFoolers2"
            user: "basicuser2"
            group: "mybasicuser2"
        cert_auth: "on"
        basic_auth: "off"
        default_basic_user: "admin"
```

The first configuration also allows a different user set for basic auth vs cert auth.

Also, the key `default_basic_user` should be named `default_admin_user`, but to avoid breaking changes...just use it "as is" to indicate the admin user.
