### ISSUE TITLE
authn change breaks existing configs

### ISSUE THREAD

**Issue by joejulian** [samsung-cnct/k2#667]
With an authn like:
```
        basic:
        - user: admin
          group: system:masters
          password: supersecret
```
and no "cert" section, up fails as kubectl does not have the permissions to `get nodes`.

**Comment by mikeln** [comment]
that was well tested and did work.  
are you running 1.6?

**Comment by joejulian** [comment]
Yes.

Renaming "basic" to "cert" fixed it for this config file.

**Comment by mikeln** [comment]
basic should/did still work....checking now.

**Comment by mikeln** [comment]
Just ran off an older branch (friday) and it worked fine with basic: only.
Still attempting to get master/latest to run.

**Comment by mikeln** [comment]
ok, finally.   Ran master/latest  with this auth config worked fine.... :
```
 &rbacKubeAuth
      authz:
        rbac:
          # super_user is required until kubernetes 1.5 is no longer supported by k2.
          # It is not used by kubernetes 1.6 or later.
          super_user: "placeholder"
      authn:
        basic:
          -
            user: "admin"
            password: "bogusthing"
            group: "system:masters"
        default_basic_user: "admin"
```

**Comment by mikeln** [comment]
Reran, with current, and previous, version of calicoNode to see if it had and CNI impacts.
```
calicoNode:
            #version: v1.2.1
            version: v1.1.3
            location: quay.io/calico/node
```
(we haven't moved our default up to 1.2.1 yet).
Didn't matter though.
