### ISSUE TITLE
`kraken.readiness` should check node status

### ISSUE THREAD

**Issue by davidewatson** [samsung-cnct/k2#766]
The `kraken.readiness` role counts lines without checking node status according to k8s. This can result in `kraken.readiness` succeeding too soon, which can then cause `kraken.services` to fail unnecessarily.

This is the current code:

```yaml
- name: Get all nodes
  command: >
    {{ kubectl }} --kubeconfig={{ kubeconfig | expanduser }} get nodes --no-headers=true --v 7
  register: job_get_nodes_result
  until: job_get_nodes_result.stdout_lines | length >= needed_nodes | int
  retries: "{{ (( readiness_wait | int ) / retry_interval | int ) | int }}"
  delay: "{{ retry_interval }}"
```

An example:

`kraken.readiness` completes:

> FAILED - RETRYING: Get all nodes (33 retries left).
changed: [localhost]

But not all nodes are ready:

> rodin:k2 dwat$ ks get nodes
NAME                           STATUS     AGE
ip-10-0-101-90.ec2.internal    NotReady   5m
ip-10-0-123-255.ec2.internal   NotReady   5m
ip-10-0-123-99.ec2.internal    NotReady   5m
ip-10-0-134-225.ec2.internal   NotReady   28s
ip-10-0-135-158.ec2.internal   NotReady   1m
ip-10-0-137-94.ec2.internal    NotReady   5m
ip-10-0-16-17.ec2.internal     NotReady   5m
ip-10-0-181-126.ec2.internal   Ready      2m
ip-10-0-2-249.ec2.internal     Ready      5m
ip-10-0-214-51.ec2.internal    NotReady   1m
ip-10-0-230-149.ec2.internal   NotReady   2m
ip-10-0-38-49.ec2.internal     Ready      5m
ip-10-0-43-3.ec2.internal      NotReady   5m
ip-10-0-54-161.ec2.internal    NotReady   5m
ip-10-0-95-106.ec2.internal    NotReady   5m
rodin:k2 dwat$

Until later:

> rodin:k2 dwat$ ks get nodes
NAME                           STATUS    AGE
ip-10-0-101-90.ec2.internal    Ready     7m
ip-10-0-123-255.ec2.internal   Ready     7m
ip-10-0-123-99.ec2.internal    Ready     7m
ip-10-0-134-225.ec2.internal   Ready     2m
ip-10-0-135-158.ec2.internal   Ready     2m
ip-10-0-137-94.ec2.internal    Ready     6m
ip-10-0-16-17.ec2.internal     Ready     7m
ip-10-0-181-126.ec2.internal   Ready     4m
ip-10-0-2-249.ec2.internal     Ready     7m
ip-10-0-214-51.ec2.internal    Ready     3m
ip-10-0-230-149.ec2.internal   Ready     4m
ip-10-0-38-49.ec2.internal     Ready     7m
ip-10-0-43-3.ec2.internal      Ready     7m
ip-10-0-54-161.ec2.internal    Ready     7m
ip-10-0-95-106.ec2.internal    Ready     7m
rodin:k2 dwat$
